name: "setup ubuntu environement"
description: "setup dotnet python and compile sirius"
inputs:
  python-version:
    description: 'python version'
    required: false
    default: '3.10'
  dotnet:
    description: 'should install dotnet ON OFF'
    required: false
    default: 'OFF'
  python:
    description: 'should install python'
    required: false
    default: 'OFF'
runs:
  using: "composite"
  steps:
    - name: Setup .NET Core 3.1
      if: ${{ inputs.dotnet == 'ON' }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Setup .NET 6.0
      if: ${{ inputs.dotnet == 'ON' }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Set up Python
      if: ${{ inputs.python == 'ON' }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ inputs.python-version }}
    - name: Pip install reqs
      if: ${{ inputs.python == 'ON' }}
      shell: bash
      run: |
        python -m pip install --upgrade pip
        python3 -m pip install mypy-protobuf absl-py setuptools wheel numpy pandas virtualenv

