name: "setup ubuntu environement"
description: "setup dotnet python and compile sirius"
inputs:
  sirius-ref:
    description: 'sirius repository ref, tag or branch'
    required: true
outputs:
  sirius-install-path:
    description: "path of the sirius installation"
    value: ${{ steps.sirius-variables.outputs.sirius-install-path }}
  sirius-archive-path:
    description: "path of the sirius archive file"
    value: ${{ steps.sirius-variables.outputs.sirius-archive-path }}
runs:
  using: "composite"
  steps:
    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.10'
    - name: Pip install reqs
      shell: bash
      run: |
        python -m pip install --upgrade pip
        python3 -m pip install mypy-protobuf absl-py setuptools wheel numpy pandas virtualenv

    - name: set sirius variables
      id: sirius-variables
      shell: bash
      run: |
        SIRIUS_WORKING_DIR=sirius-solver
        SIRIUS_BASE_PATH=${{ github.workspace }}/sirius-solver
        SIRIUS_INSTALL_DIR=SiriusInstall
        SIRIUS_INSTALL_PATH=$SIRIUS_BASE_PATH/$SIRIUS_INSTALL_DIR
        ARCHIVE_PATH="${SIRIUS_BASE_PATH}/sirius_install.tgz"
        echo "::set-output name=sirius-working-dir::$SIRIUS_WORKING_DIR"
        echo "::set-output name=sirius-base-path::$SIRIUS_BASE_PATH"
        echo "::set-output name=sirius-install-dir::$SIRIUS_INSTALL_DIR"
        echo "::set-output name=sirius-install-path::$SIRIUS_INSTALL_PATH"
        echo "::set-output name=sirius-archive-path::$ARCHIVE_PATH"

    - name: Checkout Sirius repo
      uses: actions/checkout@v2
      with:
        repository: rte-france/sirius-solver
        path: "${{ steps.sirius-variables.outputs.sirius-working-dir }}"
        ref: ${{ inputs.sirius-ref }}
    - name: Configure Sirius
      shell: bash
      run: |
        cd ${{ steps.sirius-variables.outputs.sirius-working-dir }}
        cmake -S src \
              -B build \
              -DCMAKE_BUILD_TYPE=Release \
              -DCMAKE_INSTALL_PREFIX="${{ steps.sirius-variables.outputs.sirius-install-dir }}"

    - name: Build & Install Sirius
      shell: bash
      run: |
        cd ${{ steps.sirius-variables.outputs.sirius-working-dir }}
        cmake --build build --config Release --target install -j14
        tar -czf ${{ steps.sirius-variables.outputs.sirius-archive-path }} ${{ steps.sirius-variables.outputs.sirius-install-dir }}
