name: CMake linux test

on:
  push:
    branches:
      - main
      - feature/*

jobs:
  cmake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Sirius repo
        uses: actions/checkout@v2
        with:
          repository: rte-france/sirius-solver
          path: ./sirius-solver
          ref: antares_integration
      - name: Configure Sirius
        working-directory: ./sirius-solver
        run: |
          cmake -S src \
                -B build \
                -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_INSTALL_PREFIX=SiriusInstall
      - name: Build & Install Sirius
        working-directory: ./sirius-solver
        run: cmake --build build/ --config Release --target install -j14
      - name: Upload sirius install
        uses: actions/upload-artifact@v2
        with:
          name: sirius_install
          path: ./sirius-solver/SiriusInstall
      - name: Checkout or-tools
        uses: actions/checkout@v2
        with:
          path: ./or-tools
      - name: Configure or-tools
        working-directory: ./or-tools
        run: |
          cmake -S. \
                -Bbuild \
                -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_INSTALL_PREFIX="build/install" \
                -DBUILD_SHARED_LIBS=ON \
                -DBUILD_DEPS=ON \
                -DUSE_SIRIUS=ON \
                -Dsirius_solver_DIR="${{ github.workspace }}/sirius-solver/SiriusInstall/cmake" \
                -DBUILD_PYTHON=OFF \
                -DBUILD_JAVA=OFF \
                -DBUILD_DOTNET=OFF
      - name: Build tests
        working-directory: ./or-tools
        run: |
          cmake --build build \
                --target all \
                         install \
                -j4
      - name: Prepare ortools install dyn
        working-directory: ./or-tools/build/install
        run: find bin -type f ! \( -name 'protoc*' -o -name 'scip' -o -name 'fz' \) -delete
      - name: Upload ortools install dyn
        uses: actions/upload-artifact@v2
        with:
          name: ortools_dyn_install
          path: ./or-tools/build/install
