name: Ubuntu composite

on:
  push:
    branches:
      - main
      - feature/*

jobs:

  build-ubuntu:
    runs-on: ubuntu-latest
    env:
      Sirius_Ref: antares_integration
      XPRS_Path: ${{ github.workspace }}/xpressmp813
    strategy:
      matrix:
        xprs: [ON, OFF]
        sirius: [ON, OFF]

        exclude:
          - xprs: OFF
            sirius: OFF
    name: build ubuntu sirius=${{ matrix.sirius }} xprs=${{ matrix.xprs }}

    steps:
      - name: set name variables
        id: names
        shell: bash
        run: |
          WITH_XPRS=$(( ${{ matrix.xprs }} == ON ? "_xprs" : "" ))
          WITH_SIRIUS=$(( ${{ matrix.sirius }} == ON ? "_sirius" : "" ))
          APPENDIX=$WITH_SIRIUS_$WITH_XPRS
          echo "::set-output name=appendix::$APPENDIX"
          LIB_NAME=ortools_dyn_install$WITH_SIRIUS_$WITH_XPRS
          echo "::set-output name=lib-name::$LIB_NAME"

      - name: Checkout or-tools
        uses: actions/checkout@v2

      - name: setup envoronment
        id: setup
        uses: ./.github/workflows/setup-env-ubuntu
        with:
          sirius-ref: ${{ env.Sirius_Ref }}

      - name: Upload sirius install
        uses: actions/upload-artifact@v2
        with:
          name: sirius_install
          path: ${{ steps.setup.outputs.sirius-install-path }}

      - name: Checkout xpressmp813
        uses: actions/checkout@v2
        with:
          repository: rte-france/xpress-mp
          path: ${{ env.XPRS_Path }}
          ref: master
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Configure or-tools
        run: |
          cmake -S. \
                -Bbuild \
                -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_INSTALL_PREFIX="build/install" \
                -DBUILD_SHARED_LIBS=ON \
                -DBUILD_DEPS=ON \
                -DUSE_SIRIUS=${{ matrix.sirius }} \
                -Dsirius_solver_DIR="${{ steps.setup.outputs.sirius-install-path }}/cmake" \
                -DUSE_XPRESS=${{ matrix.xprs }} \
                -DXPRESS_ROOT="${{ env.XPRS_Path }}" \
                -DBUILD_PYTHON=OFF \
                -DBUILD_JAVA=OFF \
                -DBUILD_DOTNET=OFF
      - name: Build
        run: |
          cmake --build build \
                --target all \
                install \
                -j4
      - name: Prepare ortools install dyn
        working-directory: ${{ github.workspace }}/build/install
        run: find bin -type f ! \( -name 'protoc*' -o -name 'scip' -o -name 'fz' \) -delete
      - name: Upload artifact ortools install dyn
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.names.outputs.lib-name }}
          path: ./build/install

      - name: Publish asset  file upload
        if:  github.event_name == 'release' && github.event.action == 'created'
        uses: actions/upload-release-asset@v1.0.2
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./build/install
          asset_name: ${{ steps.names.outputs.lib-name }}

